package constants

const (
	APPL_STEP_STATUS_IN_PROGRESS = "IN_PROGRESS"
	APPL_STEP_STATUS_IN_REVIEW   = "IN_REVIEW"
	APPL_STEP_STATUS_PASSED      = "PASSED"
	APPL_STEP_STATUS_REJECTED    = "REJECTED"
	APPL_STEP_STATUS_WITHDRAW    = "WITHDRAW"
	APPL_STEP_STATUS_OFFERED     = "OFFERED"
	APPL_STEP_STATUS_CANCELLED   = "CANCELLED"
	APPL_STEP_STATUS_HIRED       = "HIRED"

	HIRING_STEP_TYPE_CV_SUBMISSION = "CV_SUBMISSION"
	HIRING_STEP_TYPE_INTERVIEW     = "INTERVIEW"
	HIRING_STEP_TYPE_ASSESSMENT    = "ASSESSMENT"
)
