create table applications (
    id varchar(64) primary key,
    applicant_id varchar(64) not null,
	job_id varchar(64) not null,
	current_hiring_step_sequence INT,
	is_rejected BOOLEAN,
	is_cancelled BOOLEAN,
	is_withdrawed BOOLEAN,
	is_offered BOOLEAN,
	is_hired BOOLEAN,
    applicant_complete_name varchar(128) not null,
	applicant_gender char(1) not null,
	applicant_date_of_birth date not null,
	applicant_address varchar(1024) not null,
	applicant_profile_photo varchar(512) not null,
	applicant_profile_summary varchar(512),
	applicant_nationality varchar(4),
	applicant_country_id varchar(64),
	applicant_country_name varchar(64),
	applicant_city_id varchar(64),
	applicant_city_name varchar(64),
	applicant_is_looking_oppty varchar(64),
	applicant_education_last varchar(128),
	applicant_total_years_xp int,
	applicant_job_level_last varchar(64),
	applicant_willing_work_overseas BOOLEAN,
	applicant_expected_salary int,
	applicant_expected_salary_currency varchar(8),
    job_name varchar(256),
	job_adm_status JobAdmStatus,
	job_department_id varchar(64),
	job_department_name varchar(64),
	job_country_id varchar(64),
	job_country_name varchar(64),
	job_city_id varchar(64),
	job_city_name varchar(64),
    created_at timestamptz not null default (now()),
    updated_at timestamptz,
	deleted_at timestamptz,
	created_by varchar(64),
    created_by_name varchar(128),
	updated_by varchar(64),
    updated_by_name varchar(128),
	deleted_by varchar(64),
    deleted_by_name varchar(128)
);
